// Copyright 2020 ConsenSys Software Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by gnark DO NOT EDIT
// Modifications Copyright 2023 Tianyi Liu and Tiancheng Xie

package gpiano

import (
	"fmt"
	"io"

	curve "github.com/consensys/gnark-crypto/ecc/bn254"
)

// WriteTo writes binary encoding of Proof to w
func (proof *Proof) WriteTo(w io.Writer) (int64, error) {
	enc := curve.NewEncoder(w)
	toEncode := []interface{}{
		&proof.LRO[0], &proof.LRO[1], &proof.LRO[2],
		&proof.Z, &proof.W,
		&proof.Hx[0], &proof.Hx[1], &proof.Hx[2], &proof.Hx[3],
		&proof.Hy[0], &proof.Hy[1], &proof.Hy[2], &proof.Hy[3],
		&proof.PartialBatchedProof.H,
		proof.PartialBatchedProof.ClaimedDigests,
		&proof.PartialZShiftedProof.H,
		&proof.PartialZShiftedProof.ClaimedDigest,
		&proof.BatchedProof.H,
		proof.BatchedProof.ClaimedValues,
		&proof.WShiftedProof.H,
		&proof.WShiftedProof.ClaimedValue,
	}
	for _, value := range toEncode {
		if err := enc.Encode(value); err != nil {
			return enc.BytesWritten(), err
		}
	}
	return enc.BytesWritten(), nil
}

// ReadFrom reads binary representation of Proof from r
func (proof *Proof) ReadFrom(r io.Reader) (int64, error) {
	dec := curve.NewDecoder(r)
	toDecode := []interface{}{
		&proof.LRO[0], &proof.LRO[1], &proof.LRO[2],
		&proof.Z, &proof.W,
		&proof.Hx[0], &proof.Hx[1], &proof.Hx[2], &proof.Hx[3],
		&proof.Hy[0], &proof.Hy[1], &proof.Hy[2], &proof.Hy[3],
		&proof.PartialBatchedProof.H,
		&proof.PartialBatchedProof.ClaimedDigests,
		&proof.PartialZShiftedProof.H,
		&proof.PartialZShiftedProof.ClaimedDigest,
		&proof.BatchedProof.H,
		&proof.BatchedProof.ClaimedValues,
		&proof.WShiftedProof.H,
		&proof.WShiftedProof.ClaimedValue,
	}
	for _, value := range toDecode {
		if err := dec.Decode(value); err != nil {
			return dec.BytesRead(), err
		}
	}
	return dec.BytesRead(), nil
}

// WriteTo writes binary encoding of ProvingKey to w
func (pk *ProvingKey) WriteTo(w io.Writer) (n int64, err error) {
	return 0, fmt.Errorf("not implemented")
}

// ReadFrom reads from binary representation in r into ProvingKey
func (pk *ProvingKey) ReadFrom(r io.Reader) (int64, error) {
	return 0, fmt.Errorf("not implemented")

}

// WriteTo writes binary encoding of VerifyingKey to w
func (vk *VerifyingKey) WriteTo(w io.Writer) (n int64, err error) {
	return 0, fmt.Errorf("not implemented")
}

// ReadFrom reads from binary representation in r into VerifyingKey
func (vk *VerifyingKey) ReadFrom(r io.Reader) (int64, error) {
	return 0, fmt.Errorf("not implemented")
}
